### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#11]
Hi Dominik,

I'm still not sure how to include (i.e., what code to use) for private notes that I would like to add to the transcription as I go along. Any ideas? The <note> markup in TEI is for notes in the witness, such as marginal or interlinear notes. What code should I use to add a note for myself or for you, such as 'I'm not sure about the letters kramat, please check again'?

Best wishes,

Jason

**Comment by wujastyk** [comment]
So with the kramat it's easy: say `<unclear>kramat</unclear>`.

But for the more general case, I don't know at the moment.  I think the `<note>` mechanism is probably the way to go, perhaps using the @type attribute:

![image](https://user-images.githubusercontent.com/762246/98449215-04848b80-20ef-11eb-9931-1d84a1d0888a.png)


We can make our own vocabulary for @type, like `<note type="editorial">what on earth is this?</note>`.  I expect you can come up with better ideas :-)  The [TEI guidelines on notes in this context](https://tei-c.org/release/doc/tei-p5-doc/en/html//examples-note.html#PH) may be suggestive.  In the TEI examples, they use `xml:id` and `target` to make sure that the note and what it's discussing are logically and accurately tied together.  It's a bit laborious, but you can see it would aid precision.

**Comment by Jegb1972** [comment]
Hi Dominik,

Okay, I'll use this code; `<note type="editorial">what on earth is this?</note>`
