### ISSUE TITLE
"nothing" crossed out.

### ISSUE THREAD

**Issue by wujastyk** [wujastyk/sushrutaproject#12]
Jason, at 1.1.8.3
```
<l xml:id="Su.1.1.8.3">kāyacikītsā nāma sarvaśarīrāvasthitā<del rend="crossed out"
              /><supplied>nāṃ vyā</supplied>dhīnām upaśamakaraṇārthaṃ
            jvāraśāhvagulmaraktapittonmādāpasmārapramehātisārādīnāñ ca |</l>
```
you have an empty "del" element between -_sthitā_ and _nāṃ_. It's not incorrect XML: it validates.  But I don't know what you mean, editorially.  It suggests that nothing is being flagged as having been crossed out.  The `<del> ... </del>` elements should enclose whatever was crossed out.  If there's actually a gap, it's a `<gap>`.  If there's something crossed out that can't be read, then I think `<del extent="two" unit="akṣaras"/>` might capture the idea. Or maybe `<del><unclear extent="two" unit="akṣaras"/></del>`.  What do you think?

**Comment by Jegb1972** [comment]
HI Dominik,

Thanks for noticing this. Yes, I couldn't read what had been crossed out. I can see the number of akṣaras, so perhaps I should try <del><unclear extent="two" unit="akṣaras"/></del>

**Comment by wujastyk** [comment]
Your suggestion of `<del> rend="crossed out" extent="three" unit="akṣaras"</del>` isn't well-formed XML.  `<del rend="crossed out"  extent="two" unit="akṣaras"/>` would be okay, I think.  I need to consult the TEI guidelines and think a bit more, because this still looks to me like deleting nothing.  The MS has two aksaras that are deleted.  So there's something there that is crossed out.  But I might be wrong.

**Comment by Jegb1972** [comment]
Okay, I see how the code is supposed to work now.
