### ISSUE TITLE
<supplied></supplied>

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#14]
HI Dominik,

Do you think the `<supplied></supplied>` code the best way to make a record of emendations and conjectures as I transcribe? I know emendations, etc. are not necessary for the transcription itself, but including them as metadata in some way could be helpful for the editing  process later on.

Best wishes,

Jason

**Comment by wujastyk** [comment]
No, don't put emendations into the transcription of KL 699.  Put them into the "provisional edition".  

Against this first reaction of mine, the TEI P5 says one can use `<choice>`, `<sic>` and `<corr>` in the transcription file.  See "[correction and conjecture](https://tei-c.org/release/doc/tei-p5-doc/en/html//PH.html#PHCC)".  As it says,

> Note that the corr element is used to provide a corrected form which is not present in the source; in the case of a correction made in the source itself, whether scribal, authorial, or by some other hand, the add, del, and subst elements described in 11.3.1.4 Additions and Deletions should be used.

So I think there are two things we can do.  First, use the TEI `<choice>` method in the MS transcriptions; second - perhaps at the same time - make the provisional edition match the `<corr>` reading.

**Comment by Jegb1972** [comment]
Charles gives the following example of `<choice>`:

![choice](https://user-images.githubusercontent.com/73371402/98490318-3fb8c300-2285-11eb-9b32-2486bae185e4.jpeg)

I don't want the note to be seen in the transcription or to affect the transcribed text. What I would like to do is simply make notes as I go. In LaTeX, I would use the % sign to add notes that remain uncompiled in the pdf. 

Best wishes,

Jason

**Comment by wujastyk** [comment]
I need to think more about this business of invisible annotation.

The  XML equivalent of % is `<!-- blah blah -->`  so you can always use
that.

**Comment by Jegb1972** [comment]
How about I just enclose the invisible note in the note code. 

For example, if I wish to make the invisible note, 'could be cāyur' next to the word vāyur in the text:

vāyur`<note type="editorial"could be cāyur/>`

**Comment by wujastyk** [comment]
That won't validate.  bad XML.

Incidentally I ran oXygen's validate (ctrl+shift V) on the KL 699 file you've worked on, and it threw up quiet a few errors.  So I think you are not validating as you go along, is that right?  Or formatting (ctrl+shift V).  Both are worth doing as one goes along.  

Charles is working with a different paradigm of editing, in Saktumiva.  It's documented in his PhD thesis. 

> Li, Charles. “Limits of the Real: A Hypertext Critical Edition of Bhartṛhari’s Dravyasamuddeśa, with the Commentary of Helārāja.” Apollo - University of Cambridge Repository, 2018. [DOI](https://doi.org/10.17863/CAM.31454).

and in publications like

> Li, C. (2017). “Critical Diplomatic Editing: Applying Text-critical Principles As Algorithms.” (ed.) Boot P., Cappellotto A., Dillen W., Fischer F., Kelly A., Mertgens A., Sichani A.-M., Spadini E., & van Hulle D.Advances in Digital Scholarly Editing, Advances in Digital Scholarly Editing, pp. 305–310. Sidestone Press: Leiden. [URL](https://www.sidestone.com/bookviewer/9789088904837)

The idea is to have pure MS transcriptions, and do as much as possible of the the work of collating and editing by means of algorithms.   It shifts the attention slightly.  I'm still absorbing the ideas, myself.

**Comment by Jegb1972** [comment]
Hi Dominik,

The absence of a validation function for a single file in Oxygen came up when we last spoke. I have since written to Oxygen support about it, and I'm yet to hear from them. So, I can't validate as I go along. ctrl+shift V doesn't do anything.

About 2 hours ago, I pushed an updated version of kl_699_sutrasthana with the above code (i.e., `<note type="editorial" XXX />`). So that would obviously cause problems with validation.

I suppose it's often the case that an easy task in one system, in this case sidelining notes in Latex with %, becomes a difficult task in another. I can leave the notes out of the transcript and write them in another file (which then becomes another file to manage somehow).

Best wishes,

Jason
