### ISSUE TITLE
standardising anusvāras in the transcript

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#15]
Hi Dominik,

I probably should have raised this issue earlier, but what's your view on standardising anusvāras in the transcript? There's quite a few instances of, say, bhagavantam prakṣyati, kaumārabhṛtyan nāma, etc. 

I've been standardising them without thinking (i.e., bhagavantaṃ prakṣyati, kaumārabhṛtyaṃ nāma, etc).

But then I do record ñc, ṇṭ, etc.

Do you have a strong view on this? It's good to discuss now so I don't have to revise the transcription at a later stage.

Best, 

Jason

**Comment by wujastyk** [comment]
Please don't standardize.  Keep -m p- etc.  That's correct Sanskrit, firstly, and second this kind of thing is automatically handled by Saktumiva's "final nasal" orthographic filter:

![image](https://user-images.githubusercontent.com/762246/98486491-c369a580-21da-11eb-9baf-5e7d3546c1ad.png)

The general idea with Saktumiva is to transcribe the MSS warts and all, and to use the orthographic filters to make sure that the apparatus isn't filled with meaningless variants.  If there are filters that Charles hasn't thought of, he is quick to add them when asked.

**Comment by Jegb1972** [comment]
Okay, I won't standardise in the transcript. It will be easy to revise the transcript and correct this. yes, the filters will be important.
