### ISSUE TITLE
sections and section breaks

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#16]
Hi Dominik,

I think we may have briefly discussed the use of the vulgate's sections for labelling (xml:id="Su.1.1.8.14") but perhaps we should give it more thought before we have progressed too far in the transcription to make changes easily. The breaks and daṇḍas of KL699 do not often correspond to those of the vulgate. In most instances this is not a problem (it's just a matter of inserting a new line in the transcription), but I've hit a situation where it is, because sandhi is an issue.

The vulgate has:
1.1.14 [...] rakṣaṇaṃ ca ||
1.1.15 āyurasmin [...] ||

KL966 has:
rakṣaṇaṃ cāyurasmin

If we follow the vulgate's section breaks, these type of problems could become more common, especially if KL699 starts to deviate more from the vulgate in significant ways (in the sense of omitting or adding passages that in effect create very different sections from those of the vulgate).

The alternative is to follow the punctuation of KL699, and wherever there is a daṇḍa, we would mark the next statement as a new line. We would then use this as the benchmark for collating the other Nepalese witnesses. I suppose we would then have to change the section marks in the vulgate in order to collate the vulgate's text, which would be a headache.

Another 'possible' problem is that the punctuation of KL699 may prove to be unreliable, erratic, etc., and then we'd have to decide what to do in such cases. 

A different idea might be to insert  `<l </l>' according to the lines of the manuscript KL699. This would in effect bypass punctuation, and foreground the layout of the main witness of the critical edition. What do you think?

Anyway, I'm wondering what to do with cāyurasmin. Perhaps, the label xml:id="Su.1.1.8.14–15" is necessary here if we retain the vulgate's section breaks?

Best wishes,

Jason

**Comment by wujastyk** [comment]
I think the answer here is to make 14 and 15 a single block.  So `<xml:id="Su.1.18.14-15">`.  It will be important to use this same combined `xml:id` in all the MS transcriptions and in the provisional edition.  These `xml:id`s are how Saktumiva knows which bits of text to collate with which, across all the files.
