### ISSUE TITLE
°śiraḥpradhāna°

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#17]
Hi Dominik,

Do you think this ligature is ḥpra (f. 2r, line 2, 5 letters to the right of the right sūtra hole)?

![??](https://user-images.githubusercontent.com/73371402/98455559-5a783280-21c6-11eb-893b-119b8aa6dddb.png)

If so, I've never seen a visarga like that before.

Best wishes,

Jason

**Comment by wujastyk** [comment]
I agree it's not a visarga.  Could it be spra? Probably not. I'm also puzzled.  

Looking ahead in the vulgate edition transcription, I see .hpra in
- Su.1.5.17
- 1.21.33
- 1.24.5
- 1.26.20cd
- 1.35.12

which could be double-checked against our problem aksara.

This reminds me, I've got a concordance by Kengo and Andrey of the folios - to - passages.  I'll add it to the git repo.

Kengo's study [here](https://www.jstor.org/stable/j.ctvbkjzkh.14?seq=7#metadata_info_tab_contents) could be useful in other similar cases, but not here. It includes an aksara chart.  Cf. also [Bendall](https://archive.org/details/b30094148/page/233/mode/1up)'s charts.  There are also useful tables in L'Inde Classique, but my copies are in my office, where I almost never go at present.
