### ISSUE TITLE
Same Problem after Resolving Conflicts in Oxygen

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#18]
Hi Dominik,

I suspect I'm doing something wrong with the Github\Oxygen pull/push procedure. Can we arrange to talk sometime?

When I pull and resolve conflicts using the dual window editor, a pop-up message tells me to save the resolved file, which I must do in order to close the dual window editor. When I have saved the resolved file, then another popup window tells me to save the original file. When I try to do this, the following message comes up

> Cannot save the file: 'git://MineOriginal/01-su.su/kl_699_sutrasthana.txt' is marked as read-only.
> You must save to a different location.

I can't seem to close the dual window editor at this point. The only way I've managed to proceed is to change the file name and save to a different location.

I'm sure I'm close to getting this right, so a quick Skype may sort it out.

Best wishes,

Jason

**Comment by wujastyk** [comment]
let's have a chat tomorrow, then (or yesterday, aargh).  I'll send a calendar appointment.
