### ISSUE TITLE
validating issue

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#19]
Hi Dominik,

I've been trying to remove all validation problems from my current version of the file kl_699_sutrasthana.txt. For some unknown reason, Oxygen keeps flagging this code as a problem: 

`<unclear reason="damaged">śyate atra kasmai</unclear>`

It says the attribute "reason" is not allowed to appear in element "unclear", but I see this is recommended in both the TEI guidelines and Charles' tagging recommendations. Do you get this problem.

Oxygen also flags `<pb n="2r"/>` as a problem, saying, unexpected element "pb". But this seems correct to me.

As I think we discussed, Oxygen won't validate the metamark code, but I can't remember what we decided to do about this. So, I have changed it to an invisible note: `<!-- probable cancellation marks above a ka before kri--> `

As an aside, I just wanted to ask if all's okay on the admin side of the project? I haven't heard from Joanna or Lindsey, and just wanted to make sure that I haven't failed to reply to something or send requested information.

Thanks again.

Best wishes,

Jason

**Comment by wujastyk** [comment]
I tried both the `unclear` and `pb` strings, copied directly from your message, and neither of them caused an error in my oXygen.  Your code is correct.  Something else is going wrong.  We can look at this together in a zoom.
The issue with metamark code is that the string content of the attribute cannot have spaces.  YouHaveToUseCamelText or_else_use_underscores-or-hyphens-to-separate-words.

Best to discuss asides in personal emails.
