### ISSUE TITLE
ṛṣigaṇādhiparivṛttam KS699 f. 1v, l. 1

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#2]
Hi Dominik,

I thought this could be a good opportunity to try the issue function.

I'm not sure that KS699 (f. 1v, l. 1) reads ṛṣigaṇādhiparivṛttam. I think it has °gaṇyāparivṛttaṃ. I'm not sure about the °ṇyā°, but I don't see °ṇādhi°. What do you think?

Best wishes,

Jason

**Comment by wujastyk** [comment]
Yes, you're right, there's something wrong in my reading. There's no dha, for sure.  But I think it's just ṇa, perhaps?  Here's prāṇayātrā from the line below:
![image](https://user-images.githubusercontent.com/762246/97238895-0fb2ef80-17b0-11eb-8ab3-7f27344aa797.png)

So I now think it's ṛṣigaṇaparivṛttam.

**Comment by Jegb1972** [comment]
Yes, I agree. It's °gaṇa°. Great.
