### ISSUE TITLE
Provisional Edition

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#20]
Hi Dominik,

At least initially, I'd like to follow the punctuation of KL699 and NAK 5-333 in the provisional edition, rather than that of the printed edition. So I'd like to have the following as one sentence in the edition:

atha khalu bhagavantam amaravaram ṛṣigaṇaparivṛttam āśramasthaṃ kāśirājaṃ divodāsam aupadhenavavaitaraṇaurabhrapuṣkalāvatakaravīragopurarakṣitabhojasuśrutaprabhṛtaya ūcur bhagavañ śārīramānasāgantubhir vyādhibhir vividhavedanābhighātopadrutān sanāthān apy anāthavad viceṣṭamānān vikrośataś ca mānavānam abhisamīkṣya manasi naḥ pīḍā bhavati |

Unfortunately, we have a line break with a label after ūcur.

```
<l xml:id="Su.1.1.3">atha khalu bhagavantam amaravaram ṛṣigaṇaparivṛttam
                        āśramasthaṃ kāśirājaṃ divodāsam
                        aupadhenavavaitaraṇaurabhrapuṣkalāvatakaravīragopurarakṣitabhojasuśrutaprabhṛtaya
                        ūcur </l>
                    
                    <l xml:id="Su.1.1.4">bhagavañ śārīramānasāgantubhir vyādhibhir
                        vividhavedanābhighātopadrutān sanāthān apy anāthavad viceṣṭamānān vikrośataś
                        ca mānavānam abhisamīkṣya manasi naḥ pīḍā bhavati |
```

 I suppose we need to retain the label, but remove the line break. Is this possible?

**Comment by Jegb1972** [comment]
I was think of something like this:

```
<l xml:id="Su.1.1.3">atha khalu bhagavantam amaravaram ṛṣigaṇaparivṛttam
                        āśramasthaṃ kāśirājaṃ divodāsam
                        aupadhenavavaitaraṇaurabhrapuṣkalāvatakaravīragopurarakṣitabhojasuśrutaprabhṛtaya
                        ūcur <label>xml:id="Su.1.1.4"</label>bhagavañ śārīramānasāgantubhir vyādhibhir
                        vividhavedanābhighātopadrutān sanāthān apy anāthavad viceṣṭamānān vikrośataś
                        ca mānavānam abhisamīkṣya manasi naḥ pīḍā bhavati | teṣāṃ sukhaiṣiṇāṃ
                        rogopaśamārtham ātmanaś ca prāṇayātrārthaṃ āyurvedaṃ icchāma upadiśyamānam
                        atrāyattam aihikam āmuṣmikañ ca śreyas tad bhagavantam upapannāḥ smaḥ
                        śiṣyatve||</l>
```

**Comment by Jegb1972** [comment]
Basically, this is a formatting issue regarding Saktumiva. We need to somehow retain the label without Saktumiva beginning a new line after ūcuḥ.

**Comment by wujastyk** [comment]
One can't keep the label and remove the linebreak because the label is an "attribute" of the linebreak "element".  But we can just do away with a labelled line.
