### ISSUE TITLE
Translating technical terms

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#22]
Hi Dominik,

Is there a particular publication of yours with a glossary or translations of technical terms with the Sanskrit included? Seeing that I'm unfamiliar with many medical terms, it would be good to have such a glossary as a starting point for draft translations, which we can then refine during reading sessions. I see that you have translated these terms in Roots of Ayurveda, but that omits the Sanskrit words you were translating (for obvious reasons).

Best,

Jason

**Comment by wujastyk** [comment]
Yes, as discussed yesterday, my _Roots of Ayurveda_ book has just such a glossary, with Sanskrit.  Use the 2003 third edition if possible, since the Penguin editor and I improved the translation in a number of small but cumulative ways.
