### ISSUE TITLE
Siddham symbol in K

### ISSUE THREAD

**Issue by chakrabortydeepro** [wujastyk/sushrutaproject#266]
![image](https://github.com/wujastyk/sushrutaproject/assets/34675461/dc308a1d-48eb-459a-9a83-ffae810f6d75)
This symbol, at the beginning of K, appears to me as the Newa Siddhi sign (1144A 𑑊 NEWA SIDDHI). 
It is transcribed as oṃ in the transcription. 
` <sic ana="I do not think this is oṃ in Newari script. It appears to be a symbol indicating the beginning of the text.">oṃ</sic>`

Should we change it to `<g ref="#newa-siddhi"/>`
In that case, we should request Charles to add this symbol to Saktumiva.

**Comment by wujastyk** [comment]
Yes, and yes.  Thanks, Deepro!

**Comment by chakrabortydeepro** [comment]
Thanks, Prof. Wujastyk. Would you request Charles to add the symbol?

**Comment by wujastyk** [comment]
Will do.

**Comment by wujastyk** [comment]
Issue moved to 

- [https://github.com/chchch/upama/issues/82](https://github.com/chchch/upama/issues/82)
