### ISSUE TITLE
bad builds

### ISSUE THREAD

**Issue by wujastyk** [wujastyk/sushrutaproject#279]
@chchch 

Dear Charles, I'm getting error messages about bad builds.  E.g.,

* [https://github.com/wujastyk/sushrutaproject/actions/runs/9653723136](https://github.com/wujastyk/sushrutaproject/actions/runs/9653723136)

This started around 25 June, and I think it may be connected with an update to yarn.lock that was updated on 18 June.  But I don't really know what I'm talking about.  Could you have a look?
Best,
Dominik

**Comment by chchch** [comment]
You probably need to change these lines:

https://github.com/wujastyk/sushrutaproject/blob/main/xml/_src/config.mjs#L40-L42

Because you've renamed some files.

**Comment by wujastyk** [comment]
Thank you, Charles.

`<feeling silly/>`
