### ISSUE TITLE
Abbreviations for notes

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#3]
Dear Dominik,

I was wondering whether it is worth us formulating a set of abbreviations for notes in the transcripts. For example, it would be good to have an abbreviation for the Suśrutasaṃhitā edition by Vaidya Jādavji Trikamji Ācāryā, so that we can easily note variant readings. For example, in regard to that variant reading in the previous issue (i.e., °gaṇyāpari°), which may be an erroneous reading, it would be good to add a note like; <note>TAE: °gaṇaparivṛtam</note>.

Best wishes,

Jason

**Comment by wujastyk** [comment]
Absolutely.  I call it Ap at the moment (for Ācārya printed).  But we'll
want to distinguish his three editions.  So maybe Ap2 for the 1931 ed?
A1931? (Clear but long.)  Any suggestions?

**Comment by Jegb1972** [comment]
Yes, I like A followed by the year (i.e., A1931).

**Comment by wujastyk** [comment]
Let's go with that, then.  I'll update the files accordingly.
