### ISSUE TITLE
1.24 of NAK 5-333

### ISSUE THREAD

**Issue by wujastyk** [wujastyk/sushrutaproject#39]

**Comment by chakrabortydeepro** [comment]
Done. Should I start the next chapter?

**Comment by wujastyk** [comment]
Yes, please continue with 1.25 and beyond.  I think the KL 699 MS goes as far as 1.32 and that is all we have of the sūtrasthāna.  So at that point, let's move to the Nidānasthāna (where NAK 5-333 has been transcribed for 2.01- 2.03 (see [here](https://github.com/wujastyk/sushrutaproject/blob/main/docs/Adhy%C4%81ya%20transcriptions%20completed.md)).

Please keep an eye on [this overview of KL 699](https://github.com/wujastyk/sushrutaproject/blob/main/docs/KL%20699%20folio-text%20concordance%203%20cols.md), and feel free to update or edit it according to what you find while transcribing.

**Comment by chakrabortydeepro** [comment]
Thanks, Prof. Wujastyk. I'll do accordingly.
