### ISSUE TITLE
Su. 1.1.1 ādhyāyaṃ

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#4]
It looks to me that ādhyāyaṃ in Su. 1.1.1 has been corrected to adhyāyaṃ. The line for ā has been erased. Could this be a post correctionem, or perhaps it was done by the scribe? 

I think the possibility of a correction might be worth mentioning in the blog.

J

**Comment by wujastyk** [comment]
I agree.  It's adhyāyaṃ, after correction.  I'll fix the blog.
I've transcribed it thus:
```
vedotpattim <subst><del>ā</del><add>a</add></subst>dhyāyaṃ
```
which is what I think Charles would agree with (see [https://saktumiva.org/wiki/tei](https://saktumiva.org/wiki/tei)).

This is good for Roman, but if we also want a Devanagari edition, it would come out वेदोत्पत्तिम् अध्यायं, i.e., with the halant.  To get round that one would code
```
vedotpatti<subst><del>m ā</del><add>m a</add></subst>dhyāyaṃ
```
but honestly, that is just too ugly and annoying.

**Comment by wujastyk** [comment]
I agree.  It's adhyāyaṃ, after correction.  I'll fix the blog

**Comment by Jegb1972** [comment]
okay, great
