### ISSUE TITLE
divvodāsam

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#5]
Hi Dominik,

I probably won't be writing about issues like this every time they arise, but I thought I might try to insert a couple of screen shots to see how it goes.

![divo](https://user-images.githubusercontent.com/73371402/97241368-fe67f280-1844-11eb-9643-d6a57b2a7d48.jpeg)

I think this could be divo°. The 'o' consists of the hook before the va and the mātra after it. Like this (to):

![To](https://user-images.githubusercontent.com/73371402/97242489-1f7e1280-1848-11eb-9024-0fa0a316b8d8.jpeg)

J

**Comment by wujastyk** [comment]
Yes, again I agree.  I took it as vv, but I think the hook just looks like a closed loop.  I'll update the file. 
Your screenshots were a bit too big and grainy?

**Comment by Jegb1972** [comment]
Yes. Actually, the above screen shots are worse than the originals I took. I suppose I'll have to take screen shots without so much magnification.
