### ISSUE TITLE
How to represent Newa Old Gap filler (or Newa Conspicuous gap filler)

### ISSUE THREAD

**Issue by chakrabortydeepro** [wujastyk/sushrutaproject#55]
We come across this character a lot in NAK 5-333 and we do have some nice discussions about this character and its equivalent in certain other Eastern scripts on [blogposts](https://sushrutaproject.org/2021/04/12/conspicuous-filling-sign2/). 

But I am still not sure how we should put it on XML. I didn't find any Unicode character code for this character. This character, however, looks pretty much like Tamil letter ai (ஐ). But I don't know if this can help.

**Comment by wujastyk** [comment]
See the answer here: https://github.com/chchch/upama/issues/10#issuecomment-884070967

Let me know if this doesn't answer your query.

**Comment by chakrabortydeepro** [comment]
Thanks for your response. Charles actually gave some options. Which one are we finally opting?

He said, 

"Here are some options on how we might represent this:

~ for the "normal" gap-filler as defined in the Newa Unicode block, and <g ref="#newa-old-gap-filler">~</g> for the "old-style" one (or whatever transliteration we decide upon)

<g type="gap-filler" rendition="#newa-gap-filler"/> (which can appear as a Newa sign in IAST and Newa transliteration, but change to ꣹ in Devanāgarī)

<space type="gap-filler" rendition="#newa-gap-filler"/>

<space type="gap-filler" rendition="#newa-gap-filler" quantity="5"/> (which would give you 5 filler characters)"

Also, how should we do the old gap filler and the Jaayekaa?

**Comment by ankleb** [comment]
@chakrabortydeepro, I've started [this informal documentation](https://github.com/wujastyk/sushrutaproject/blob/main/docs/non-textual%20signs%20in%20MSS.md). I plan to work on it "on the fly", that is, just add things as I encounter them in my transcriptions. I'm currently transcribing a chapter in N, that's why I added a few glyphs from there first.
Anyways, pls contribute whenever you feel inspired.

**Comment by chakrabortydeepro** [comment]
@ankleb Thanks Andrey for this. I'll add things here as I come across them.

**Comment by wujastyk** [comment]
@chakrabortydeepro ([question](https://github.com/wujastyk/sushrutaproject/issues/55#issuecomment-958612565)): use `<g ref="#newa-gap-filler"/>` and `<g ref="#newa-old-gap-filler"/>`
