### ISSUE TITLE
Su.1.1.4

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#6]
Do you think it is worth noting the deletion between vikrośataś and ca? The two (?)deleted akṣaras have been rubbed out. How would you code this? 

<subst><del>++</del></subst>

J

**Comment by wujastyk** [comment]
generally, try as far as possible to use the codes Charles recomments [here](https://saktumiva.org/wiki/tei).  The reason is that Saktumiva is good at dealing with them appropriately.  So in this case, maybe 
```
<gap reason="erased" unit="akṣara" quantity="2"/>
```

**Comment by Jegb1972** [comment]
Okay. Now I see the schema for the code. Thanks.

**Comment by Jegb1972** [comment]
Actually, I now see that the code I wrote in my original post (in this issue) did not appear. I see the code you typed appears in a highlighted bar. I originally wrote

`<subst><del>++</del></subst> `
