### ISSUE TITLE
English and Sanskrit terms

### ISSUE THREAD

**Issue by wujastyk** [wujastyk/sushrutaproject#69]
Dear @ankleb,
please do not say,

`\item \emph{Udāvartā} (Retaining),`

but say, rather 

`\item \se{Retaining}{udāvartā}`

The latter form is better because
* it keeps English in the main English text (which is a translation, after all);
* it puts Sanskrit in parentheses for the specialists;
* The `\se{}{}`  "Sanskrit-English" command also puts both S-E and E-S entries into the index.

**Comment by wujastyk** [comment]
Similarly, please do not use *any* Sanskrit words in your English translation.  E.g., do not say,

`The \emph{Udāvartā} releases foamy \emph{ārtava} `

but say, rather,

`The retaining releases foamy menstrual blood `

(We probably need a more explanatory Engl. tr. than "retaining".)

@ankleb

**Comment by ankleb** [comment]
Okay, got it!
