### ISSUE TITLE
Punctuation

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#7]
Hi Dominik,

A general question.

I see we are following Vikramaji Ācārya's punctuation. I see a single daṇḍa after vatsāḥ. Have you considered whether it's worth reflecting the punctuation of KS699? 

J

**Comment by wujastyk** [comment]
Yes, I think we should record the punctuation of KL699.  You never know.

**Comment by Jegb1972** [comment]
I see that you are following KL699's punctuation. The <l xml:id="Su.1.1.4"> is just a label. okay.

Yes, maybe if the punctuation of KL699 works well, it should be adopted throughout.

J

**Comment by wujastyk** [comment]
Saying "adopted" implies a question about what we're doing.  The XML file
we're making is a diplomatic transcription of KL 699.  Warts and all.
Daṇḍas wherever they fall.  No corrections, no judgements.

Separately, we will probably wish to establish an edition.  It could be an
edition based on KL 699 alone.  So, KL 699 embellished sensible readings
and emendations and conjectures.  Or we could do an edition of the three
old Kathmandu MSS, K 699, NAK 1-1079 and NAK 5-333.  But we don't know
enough yet to decide whether two or three of these amount to a meaningful
recension.  So let's keep transcribing for an adhyāya or so, and then think
about it.

**Comment by Jegb1972** [comment]
Yes, I agree. I meant, '[...] adopted throughout [the edition].'

Also, I see that I again typed code into my previous post that disappeared. I meant to say, 'The `<l xml:id="Su.1.1.1">` is just a label. 

So, I now see that Su.1.1.1 is metadata, and not part of the transcribed text.

**Comment by wujastyk** [comment]
On Mon, 26 Oct 2020 at 23:37, Jegb1972 <notifications@github.com> wrote:

> Also, I see that I again typed code into my previous post that disappeared. I meant to say, The `<l xml:id="Su.1.1.1">` is just a label.

Yes.  When messages typing in Github, if you put a left quote, `, before and after your text, that text will be quoted verbatim.  
If you have more than a couple of words, put three left quotes, ```, above and below the text and it will be quoted verbatim as a paragraph.

And to the point, yes,  `<l xml:id="Su.1.1.1">` is metadata.  So the `<l>` is the start-line element, and the `xml:id="xxx"` bit is the so-called attribute.  All that is XML and not transcribed MS text.  The scaffolding, not the building.
These xml:id codes are important because Saktumiva uses them in order to know what to collate with what.  Saktumiva will look through all the transcribed MSS, find all the chunks with the same xml:id label and collate them against each other.  So these labels need to refer to the same chunks of text across all the texts we transcribe.
